services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: BookStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bookstore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookstore.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bookstore

  migrator:
    build:
      context: .
      dockerfile: ./src/Acme.BookStore.DbMigrator/Dockerfile
    environment:
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=BookStore;User ID=postgres;Password=123456;"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bookstore
    profiles:
      - migrate

  backend:
    build:
      context: .
      dockerfile: ./src/Acme.BookStore.HttpApi.Host/Dockerfile
    environment:
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=BookStore;User ID=postgres;Password=123456;"
      App__SelfUrl: "http://localhost:8080"
      App__AngularUrl: "http://localhost:4200"
      App__CorsOrigins: "http://localhost:4200"
      App__RedirectAllowedUrls: "http://localhost:4200"
      AuthServer__Authority: "http://localhost:8080"
      AuthServer__RequireHttpsMetadata: "false"
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./Logs:/app/Logs
    networks:
      - bookstore

  frontend:
    build:
      context: ./angular
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - bookstore
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - bookstore
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bookstore
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - bookstore

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - ./Logs:/app/Logs:ro
    depends_on:
      - loki
    networks:
      - bookstore


volumes:
  postgres_data:
  grafana_data:

networks:
  bookstore: